# Generated by Django 2.0 on 2017-12-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20171228_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
    ]
