# Generated by Django 2.0 on 2018-01-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20171229_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
