# Generated by Django 2.0 on 2017-12-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_auto_20171228_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='ended',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
