# Generated by Django 2.0 on 2017-12-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_auto_20171228_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employment',
            new_name='Employer',
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name_plural': 'Employer'},
        ),
    ]
