# Generated by Django 2.0 on 2018-01-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0006_employer_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='current',
        ),
    ]
