# Generated by Django 2.0 on 2017-12-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbs', '0002_proverb_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='proverb',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
