# Generated by Django 2.0 on 2017-12-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbs', '0003_proverb_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proverb',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
